name: CI + CD on Ubuntu

on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests (CI)
        run: npm test

      - name: Build Docker image (CD)
        run: docker build -t ubuntu-test-app .

      - name: Run container (simulate deploy)
        run: docker run --rm ubuntu-test-app

